"""init

Revision ID: bd62b9864f56
Revises: 
Create Date: 2022-03-16 14:07:59.891561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd62b9864f56'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CustomerUsers',
    sa.Column('CUST_ID', sa.BigInteger(), nullable=False),
    sa.Column('USER_ID', sa.BigInteger(), nullable=False),
    sa.Column('USERNAME_EMAIL', sa.VARCHAR(length=60), nullable=False),
    sa.Column('PASSWORD_HASH', sa.VARCHAR(length=80), nullable=False),
    sa.Column('CUST_CONTACT_NAME', sa.VARCHAR(length=25), nullable=True),
    sa.Column('CUST_CONTACT_PHONE_EXT', sa.VARCHAR(length=20), nullable=True),
    sa.Column('CUST_CONTACT_CELL_PHONE', sa.VARCHAR(length=20), nullable=True),
    sa.Column('CUST_CONTACT_EMAIL', sa.VARCHAR(length=48), nullable=True),
    sa.Column('ACCOUNT_ADMIN', sa.VARCHAR(length=1), nullable=True),
    sa.Column('READ_ONLY_MANUALS', sa.VARCHAR(length=1), nullable=True),
    sa.Column('READ_ONLY_SCHEDULING', sa.VARCHAR(length=1), nullable=True),
    sa.Column('READ_ONLY_PRICE_LIST', sa.VARCHAR(length=1), nullable=True),
    sa.Column('READ_ONLY_ORDER_HISTORY', sa.VARCHAR(length=1), nullable=True),
    sa.Column('KIT_ORDER_ACCESS', sa.VARCHAR(length=1), nullable=True),
    sa.Column('PARTS_ORDER_ACCESS', sa.VARCHAR(length=1), nullable=True),
    sa.Column('ACTIVE', sa.VARCHAR(length=1), nullable=True),
    sa.PrimaryKeyConstraint('CUST_ID', 'USER_ID', name=op.f('pk_CustomerUsers')),
    sa.UniqueConstraint('USERNAME_EMAIL', name=op.f('uq_CustomerUsers_USERNAME_EMAIL'))
    )
    op.create_table('Customers',
    sa.Column('CUST_ID', sa.BigInteger(), nullable=False),
    sa.Column('CUST_NAME', sa.VARCHAR(length=50), nullable=True),
    sa.Column('CUST_ADDRESS1', sa.VARCHAR(length=50), nullable=True),
    sa.Column('CUST_ADDRESS2', sa.VARCHAR(length=50), nullable=True),
    sa.Column('CUST_CITY', sa.VARCHAR(length=50), nullable=True),
    sa.Column('CUST_PROV_STATE', sa.VARCHAR(length=50), nullable=True),
    sa.Column('CUST_COUNTRY', sa.VARCHAR(length=50), nullable=True),
    sa.Column('CUST_POSTAL_ZIP', sa.VARCHAR(length=16), nullable=True),
    sa.Column('SHIP_NAME', sa.VARCHAR(length=50), nullable=True),
    sa.Column('SHIP_ADDRESS1', sa.VARCHAR(length=50), nullable=True),
    sa.Column('SHIP_ADDRESS2', sa.VARCHAR(length=50), nullable=True),
    sa.Column('SHIP_CITY', sa.VARCHAR(length=50), nullable=True),
    sa.Column('SHIP_PROV_STATE', sa.VARCHAR(length=50), nullable=True),
    sa.Column('SHIP_COUNTRY', sa.VARCHAR(length=50), nullable=True),
    sa.Column('SHIP_POSTAL_ZIP', sa.VARCHAR(length=16), nullable=True),
    sa.Column('CUST_PHONE1', sa.VARCHAR(length=20), nullable=True),
    sa.Column('IS_DEALER', sa.VARCHAR(length=1), nullable=True),
    sa.Column('IS_REPAIR_FACILITY', sa.VARCHAR(length=1), nullable=True),
    sa.Column('DEALER_CLASS', sa.VARCHAR(length=1), nullable=True),
    sa.Column('CUST_CREDIT_RATING', sa.VARCHAR(length=12), nullable=True),
    sa.Column('DROP_DECK_TRAILERS', sa.VARCHAR(length=1), nullable=True),
    sa.Column('CURRENCY', sa.VARCHAR(length=3), nullable=True),
    sa.PrimaryKeyConstraint('CUST_ID', name=op.f('pk_Customers'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Customers')
    op.drop_table('CustomerUsers')
    # ### end Alembic commands ###
